alias: Send alert when water leak stopped
description: ""
trigger:
  - type: not_moist
    platform: device
    device_id: fbaa16d6de404f0bb3a2b742ec84bce0
    entity_id: binary_sensor.water_guard_leak_alarm
    domain: binary_sensor
condition: []
action:
  - service: telegram_bot.send_message
    data:
      message: Vannlekkasje fikset.
mode: single
